[package]
name = "ape"
description = "ANSI/POSIX Environment for Glenda Microkernel"
version = "0.1.0"
edition = "2024"

[dependencies]
libglenda-rs = { path = "../../lib/libglenda-rs", features = [
    "rt-service",
    "vspacemgr_check_bypass",
] }
libape = { package = "libape", path = "../../lib/libape", default-features = false }
linux-raw-sys = { version = "0.12.1", default-features = false, features = [
    "no_std",
    "errno",
    "general",
    "auxvec",
    "elf",
    "elf_uapi",
    "ioctl",
    "system",
] }
serde = { version = "1.0", default-features = false, features = [
    "derive",
    "alloc",
] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
anstyle-parse = { version = "0.2.7", default-features = false, features = ["utf8"] }

[features]
strace = []
