#![allow(non_upper_case_globals)]

use linux_raw_sys::general::*;

pub(crate) fn syscall_name(sys_num: u32) -> &'static str {
    match sys_num {
        __NR_set_tid_address => "set_tid_address",
        __NR_gettid => "gettid",
        __NR_getpid => "getpid",
        __NR_getppid => "getppid",
        __NR_exit => "exit",
        __NR_exit_group => "exit_group",
        __NR_brk => "brk",
        __NR_mmap => "mmap",
        __NR_mprotect => "mprotect",
        __NR_munmap => "munmap",
        __NR_lseek => "lseek",
        __NR_fcntl => "fcntl",
        __NR_ioctl => "ioctl",
        __NR_read => "read",
        __NR_write => "write",
        __NR_readv => "readv",
        __NR_writev => "writev",
        __NR_openat => "openat",
        __NR_close => "close",
        __NR_getcwd => "getcwd",
        __NR_chdir => "chdir",
        __NR_fchdir => "fchdir",
        __NR_chroot => "chroot",
        __NR_uname => "uname",
        __NR_rt_sigsuspend => "rt_sigsuspend",
        __NR_rt_sigaction => "rt_sigaction",
        __NR_rt_sigprocmask => "rt_sigprocmask",
        __NR_rt_sigpending => "rt_sigpending",
        __NR_rt_sigtimedwait => "rt_sigtimedwait",
        __NR_set_robust_list => "set_robust_list",
        __NR_prlimit64 => "prlimit64",
        __NR_clock_gettime => "clock_gettime",
        __NR_gettimeofday => "gettimeofday",
        __NR_nanosleep => "nanosleep",
        __NR_ppoll => "ppoll",
        __NR_getrandom => "getrandom",
        __NR_getuid => "getuid",
        __NR_geteuid => "geteuid",
        __NR_getgid => "getgid",
        __NR_getegid => "getegid",
        __NR_execve => "execve",
        __NR_clone => "clone",
        __NR_wait4 => "wait4",
        __NR_setsid => "setsid",
        __NR_getsid => "getsid",
        __NR_setpgid => "setpgid",
        __NR_getpgid => "getpgid",
        __NR_kill => "kill",
        __NR_reboot => "reboot",
        __NR_sched_yield => "sched_yield",
        __NR_prctl => "prctl",
        __NR_futex => "futex",
        _ => "unknown",
    }
}
