pub use glenda::cap::{CapPtr, Endpoint};
pub const INIT_SLOT: CapPtr = CapPtr::from(9);
pub const INIT_CAP: Endpoint = Endpoint::from(INIT_SLOT);
pub const VT_SLOT: CapPtr = CapPtr::from(10);
pub const VT_CAP: Endpoint = Endpoint::from(VT_SLOT);
pub const FS_SLOT: CapPtr = CapPtr::from(11);
pub const FS_CAP: Endpoint = Endpoint::from(FS_SLOT);
pub const VOLUME_SLOT: CapPtr = CapPtr::from(12);
pub const VOLUME_CAP: Endpoint = Endpoint::from(VOLUME_SLOT);
pub const DEFAULT_VT_NAME: &str = "vt0";
pub const DEFAULT_INIT_PROCESS_NAME: &str = "init";
pub const DEFAULT_INIT_PROGRAM: &str = "/init";
pub const VSPACE_SCRATCH_START: usize = 0x7000_0000;
pub const VSPACE_SCRATCH_END: usize = 0x8000_0000;
pub const DEFAULT_PROCESS_ROOT: &str = "/linux";
