use glenda::arch::mem::PGSIZE;
use glenda::cap::{CapPtr, Endpoint};
use glenda::mem::{HEAP_VA, THREAD_AREA_BASE};
use linux_raw_sys::general::{SIGBUS, SIGILL, SIGSEGV, SIGTRAP, STDERR_FILENO};

pub const INIT_SLOT: CapPtr = CapPtr::from(9);
pub const INIT_CAP: Endpoint = Endpoint::from(INIT_SLOT);
pub const VT_SLOT: CapPtr = CapPtr::from(10);
pub const VT_CAP: Endpoint = Endpoint::from(VT_SLOT);
pub const FS_SLOT: CapPtr = CapPtr::from(11);
pub const FS_CAP: Endpoint = Endpoint::from(FS_SLOT);
pub const VOLUME_SLOT: CapPtr = CapPtr::from(12);
pub const VOLUME_CAP: Endpoint = Endpoint::from(VOLUME_SLOT);
pub const ROOTFS_SLOT: CapPtr = CapPtr::from(13);
pub const ROOTFS_CAP: Endpoint = Endpoint::from(ROOTFS_SLOT);
pub const STDIO_SLOT: CapPtr = CapPtr::from(14);
pub const STDIO_CAP: Endpoint = Endpoint::from(STDIO_SLOT);
pub const TIME_SLOT: CapPtr = CapPtr::from(15);
pub const TIME_CAP: Endpoint = Endpoint::from(TIME_SLOT);
pub const AUTH_SLOT: CapPtr = CapPtr::from(16);
pub const AUTH_CAP: Endpoint = Endpoint::from(AUTH_SLOT);
pub const CSPACE_DYNAMIC_L1_START_SLOT: usize = 32;
pub const DEFAULT_VT_NAME: &str = "vt0";
pub const DEFAULT_INIT_PROCESS_NAME: &str = "init";
pub const DEFAULT_INIT_PROGRAM: &str = "/init";
pub const VSPACE_SCRATCH_START: usize = 0x7000_0000;
pub const VSPACE_SCRATCH_END: usize = 0x8000_0000;
pub const DEFAULT_PROCESS_ROOT: &str = "/";
pub const DEFAULT_VIEW_ROOT: &str = "/linux";
pub const FIRST_USER_FD: u32 = STDERR_FILENO + 1;
pub const DEFAULT_MAX_STACK_SIZE: usize = 8 * 1024 * 1024;
pub const DEFAULT_MMAP_BASE: usize = HEAP_VA + 16 * PGSIZE;
pub const DEFAULT_MMAP_LIMIT: usize = THREAD_AREA_BASE - 16 * PGSIZE;
pub const DEFAULT_HEAP_LIMIT: usize = DEFAULT_MMAP_BASE;
pub const APE_SLOT: CapPtr = CapPtr::from(11);
pub const APE_CAP: Endpoint = Endpoint::from(APE_SLOT);
pub const FS_ASYNC_POOL_BASE_VADDR: usize = 0x5800_0000;
pub const FS_ASYNC_POOL_MAX_REGIONS: usize = 64;
pub const APE_ASYNC_WORKER_COUNT: usize = 1;
pub const APE_ASYNC_WORKER_STACK_SIZE: usize = 64 * 1024;
pub const APE_ASYNC_WORKER_STACK_PAGES: usize = APE_ASYNC_WORKER_STACK_SIZE / PGSIZE;
pub const APE_ASYNC_WORKER_STACK0_BASE: usize = 0x5760_0000;
pub const APE_ASYNC_NOTIFY_BADGE_BITS: usize = 1usize << (usize::BITS as usize - 1);
pub const APE_DISPATCHER_COUNT: usize = 1;
pub const APE_DISPATCHER_STACK_SIZE: usize = 64 * 1024;
pub const APE_DISPATCHER_STACK_PAGES: usize = APE_DISPATCHER_STACK_SIZE / PGSIZE;
pub const APE_DISPATCHER_STACK0_BASE: usize = 0x5740_0000;
pub const APE_DISPATCHER_STACK_SPAN: usize = 0x20_000;
